// Hardcoded demo data for public demo mode (no authentication required)

export const demoPortfolio = {
    totalValue: 132832.50,
    totalCost: 114380.20,
    totalProfitLoss: 18452.30,
    totalProfitLossPercentage: 16.13,
    cashBalanceUSD: 15000.0,
    cashBalanceARS: 5000000.0,
    totalPatrimony: 147832.50,
    positionCount: 5,
    positions: [
        {
            id: "demo-pos-1",
            assetId: "demo-asset-1",
            symbol: "BTC",
            name: "Bitcoin",
            image: "https://assets.coingecko.com/coins/images/1/large/bitcoin.png",
            quantity: 0.85,
            averageBuyPrice: 62000.0,
            currentPrice: 97450.0,
            currentValue: 82832.50,
            totalValue: 82832.50,
            cost: 52700.0,
            totalCost: 52700.0,
            profitLoss: 30132.50,
            profitLossPercentage: 57.18,
            priceChange24h: 2.34,
            allocation: 62.36,
            coinGeckoId: "bitcoin",
        },
        {
            id: "demo-pos-2",
            assetId: "demo-asset-2",
            symbol: "ETH",
            name: "Ethereum",
            image: "https://assets.coingecko.com/coins/images/279/large/ethereum.png",
            quantity: 8.5,
            averageBuyPrice: 3200.0,
            currentPrice: 3680.0,
            currentValue: 31280.0,
            totalValue: 31280.0,
            cost: 27200.0,
            totalCost: 27200.0,
            profitLoss: 4080.0,
            profitLossPercentage: 15.0,
            priceChange24h: 1.12,
            allocation: 23.54,
            coinGeckoId: "ethereum",
        },
        {
            id: "demo-pos-3",
            assetId: "demo-asset-3",
            symbol: "SOL",
            name: "Solana",
            image: "https://assets.coingecko.com/coins/images/4128/large/solana.png",
            quantity: 50,
            averageBuyPrice: 180.0,
            currentPrice: 210.0,
            currentValue: 10500.0,
            totalValue: 10500.0,
            cost: 9000.0,
            totalCost: 9000.0,
            profitLoss: 1500.0,
            profitLossPercentage: 16.67,
            priceChange24h: 3.45,
            allocation: 7.9,
            coinGeckoId: "solana",
        },
        {
            id: "demo-pos-4",
            assetId: "demo-asset-4",
            symbol: "ADA",
            name: "Cardano",
            image: "https://assets.coingecko.com/coins/images/975/large/cardano.png",
            quantity: 12000,
            averageBuyPrice: 0.58,
            currentPrice: 0.52,
            currentValue: 6240.0,
            totalValue: 6240.0,
            cost: 6960.0,
            totalCost: 6960.0,
            profitLoss: -720.0,
            profitLossPercentage: -10.34,
            priceChange24h: -1.87,
            allocation: 4.7,
            coinGeckoId: "cardano",
        },
        {
            id: "demo-pos-5",
            assetId: "demo-asset-5",
            symbol: "DOT",
            name: "Polkadot",
            image: "https://assets.coingecko.com/coins/images/12171/large/polkadot.png",
            quantity: 250,
            averageBuyPrice: 8.08,
            currentPrice: 7.92,
            currentValue: 1980.0,
            totalValue: 1980.0,
            cost: 2020.2,
            totalCost: 2020.2,
            profitLoss: -40.2,
            profitLossPercentage: -1.99,
            priceChange24h: -0.54,
            allocation: 1.49,
            coinGeckoId: "polkadot",
        },
    ],
};

export const demoTransactions = {
    transactions: [
        {
            id: "demo-tx-1",
            type: "DEPOSIT_USD",
            quantity: null,
            pricePerUnit: null,
            totalAmount: 50000.0,
            currency: "USD",
            createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
            asset: null,
        },
        {
            id: "demo-tx-2",
            type: "DEPOSIT_ARS",
            quantity: null,
            pricePerUnit: null,
            totalAmount: 5000000.0,
            currency: "ARS",
            createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
            asset: null,
        },
        {
            id: "demo-tx-3",
            type: "BUY",
            quantity: 0.5,
            pricePerUnit: 58000.0,
            totalAmount: 29000.0,
            currency: "USD",
            createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
            asset: { symbol: "BTC", name: "Bitcoin", image: "https://assets.coingecko.com/coins/images/1/large/bitcoin.png" },
        },
        {
            id: "demo-tx-4",
            type: "BUY",
            quantity: 5.0,
            pricePerUnit: 3100.0,
            totalAmount: 15500.0,
            currency: "USD",
            createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
            asset: { symbol: "ETH", name: "Ethereum", image: "https://assets.coingecko.com/coins/images/279/large/ethereum.png" },
        },
        {
            id: "demo-tx-5",
            type: "BUY",
            quantity: 0.35,
            pricePerUnit: 67000.0,
            totalAmount: 23450.0,
            currency: "USD",
            createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
            asset: { symbol: "BTC", name: "Bitcoin", image: "https://assets.coingecko.com/coins/images/1/large/bitcoin.png" },
        },
        {
            id: "demo-tx-6",
            type: "BUY",
            quantity: 50.0,
            pricePerUnit: 180.0,
            totalAmount: 9000.0,
            currency: "USD",
            createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
            asset: { symbol: "SOL", name: "Solana", image: "https://assets.coingecko.com/coins/images/4128/large/solana.png" },
        },
        {
            id: "demo-tx-7",
            type: "BUY",
            quantity: 3.5,
            pricePerUnit: 3340.0,
            totalAmount: 11690.0,
            currency: "USD",
            createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
            asset: { symbol: "ETH", name: "Ethereum", image: "https://assets.coingecko.com/coins/images/279/large/ethereum.png" },
        },
        {
            id: "demo-tx-8",
            type: "BUY",
            quantity: 12000,
            pricePerUnit: 0.58,
            totalAmount: 6960.0,
            currency: "USD",
            createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
            asset: { symbol: "ADA", name: "Cardano", image: "https://assets.coingecko.com/coins/images/975/large/cardano.png" },
        },
        {
            id: "demo-tx-9",
            type: "BUY",
            quantity: 250,
            pricePerUnit: 8.08,
            totalAmount: 2020.0,
            currency: "USD",
            createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
            asset: { symbol: "DOT", name: "Polkadot", image: "https://assets.coingecko.com/coins/images/12171/large/polkadot.png" },
        },
        {
            id: "demo-tx-10",
            type: "SELL",
            quantity: 0.1,
            pricePerUnit: 95000.0,
            totalAmount: 9500.0,
            currency: "USD",
            createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
            asset: { symbol: "BTC", name: "Bitcoin", image: "https://assets.coingecko.com/coins/images/1/large/bitcoin.png" },
        },
        {
            id: "demo-tx-11",
            type: "DEPOSIT_USD",
            quantity: null,
            pricePerUnit: null,
            totalAmount: 15000.0,
            currency: "USD",
            createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
            asset: null,
        },
    ],
    total: 11,
    page: 1,
    limit: 20,
    totalPages: 1,
};

export const demoAdvisor = {
    overallScore: 72,
    diversificationScore: 65,
    riskScore: 58,
    performanceScore: 85,
    alerts: [
        {
            type: "warning" as const,
            title: "Concentración en Bitcoin",
            message:
                "Bitcoin representa el 62% de tu portfolio. Considerá diversificar para reducir el riesgo.",
        },
        {
            type: "info" as const,
            title: "Buen rendimiento general",
            message:
                "Tu portfolio tiene un rendimiento del +16.1%. Superás al promedio del mercado.",
        },
        {
            type: "danger" as const,
            title: "Cardano en pérdida",
            message:
                "Tu posición en ADA está en -10.3%. Evaluá si mantener o aumentar para promediar.",
        },
    ],
    recommendations: [
        "Diversificá en stablecoins para reducir la volatilidad del portfolio.",
        "Considerá tomar ganancias parciales en Bitcoin dado el alto rendimiento.",
        "Aumentá la posición en Ethereum, que tiene buenos fundamentales a largo plazo.",
        "Rebalanceá el portfolio para que ningún activo supere el 40% de asignación.",
    ],
    assetAnalysis: [
        {
            symbol: "BTC",
            name: "Bitcoin",
            riskLevel: "medio" as const,
            profitLoss: 57.18,
            recommendation: "Tomar ganancias parciales",
        },
        {
            symbol: "ETH",
            name: "Ethereum",
            riskLevel: "medio" as const,
            profitLoss: 15.0,
            recommendation: "Mantener posición",
        },
        {
            symbol: "SOL",
            name: "Solana",
            riskLevel: "alto" as const,
            profitLoss: 16.67,
            recommendation: "Mantener con atención",
        },
        {
            symbol: "ADA",
            name: "Cardano",
            riskLevel: "alto" as const,
            profitLoss: -10.34,
            recommendation: "Evaluar DCA o salir",
        },
        {
            symbol: "DOT",
            name: "Polkadot",
            riskLevel: "medio" as const,
            profitLoss: -1.99,
            recommendation: "Mantener posición",
        },
    ],
};

export const demoDolar = {
    compra: 1180.0,
    venta: 1220.0,
    fechaActualizacion: new Date().toISOString(),
};
